name: Copy tvbox source to textdb
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch original source json
        run: |
          curl -L "https://tvbox.xiaoy93.ccwu.cc/" -o source_raw.json

      - name: Upload to TextDB
        env:
          TEXTDB_KEY: ${{ secrets.TEXTDB_KEY }}
        run: |
          # 读取文件内容并URL编码
          CONTENT=$(jq -sR @uri source_raw.json)
          res=$(curl -L -X POST "https://api.textdb.online/update/" \
            -d "key=${TEXTDB_KEY}" \
            -d "value=${CONTENT}")
          echo "textdb响应: $res"
