name: Sync TVBox Config to textdb
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and modify config
        run: |
          curl -L "https://tvbox.xiaoy93.ccwu.cc" -o config.json
          sed -i 's|https://raw.githubusercontent.com|https://ghfast.top/https://raw.githubusercontent.com|g' config.json

      - name: Push to TextDB
        env:
          TEXTDB_KEY: ${{ secrets.TEXTDB_KEY }}
        run: |
          curl -X POST "https://textdb.online/update/?key=${TEXTDB_KEY}" \
            -H "Content-Type: text/plain;charset=utf-8" \
            --data-binary @config.json
